name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: 'master'
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2.5.0
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - id: install
      run: yarn install --frozen-lockfile
    - name: Set up GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: imaware-test
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - id: integration
      run: yarn test:integration
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      with:
        semantic_version: 17.3.7