name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
        token: ${{ secrets.BOT_TOKEN }}
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2.5.2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - id: install
      run: yarn install --frozen-lockfile
    # Setup gcloud CLI
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.IMAWARE_TEST_WIP }}
        service_account: ${{ secrets.IMAWARE_TEST_WIP_SERVICE_ACCOUNT }}

    - name: Set up GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - id: integration
      run: yarn test:integration
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17.3.7
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
